<?php

namespace Platform\Controllers\Campaign;

use App\Http\Controllers\Controller;
use Carbon\Carbon;
use App\Staff;
use App\Customer;
use Platform\Models\Code;
use Platform\Models\History;
use App\Http\Controllers;
use Platform\Controllers\Core;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Illuminate\Validation\Rule;
use Barzo\Password\Generator;

class PointController extends Controller
{

  /*
     |--------------------------------------------------------------------------
     | Points related functions
     |--------------------------------------------------------------------------
     */

  /**
   * Get customer points.
   *
   * @return \Symfony\Component\HttpFoundation\Response 
   */
  public function getCustomerPoints(Request $request)
  {
    $campaign = \Platform\Models\Campaign::withoutGlobalScopes()->whereUuid(request('uuid', 0))->firstOrFail();
    $user = Customer::withoutGlobalScopes()->where('id', Auth::user('customer')->id)->where('campaign_id', $campaign->id)->firstOrFail();

    return response()->json($user->points);
  }

  /**
   * Get code used to claim points with a link (e.g. QR code).
   *
   * @return \Symfony\Component\HttpFoundation\Response 
   */
  public function postGetClaimToken(Request $request)
  {
    $account = app()->make('account');
    $campaign = \Platform\Models\Campaign::withoutGlobalScopes()->whereUuid(request('campaign', 0))->firstOrFail();

    // First, delete existing codes
    $deletedRows = Code::where('type', 'token')->where('customer_id', auth('customer')->user()->id)->delete();

    // Add generated code to codes table, expire in 1 hour
    $token = $this->getUniqueCode('token', $campaign->id);
    $expires_at = Carbon::now()->addHours(1);

    $code = new Code;
    $code->campaign_id = $campaign->id;
    $code->customer_id = auth('customer')->user()->id;
    $code->type = 'token';
    $code->code = $token;
    $code->expires_at = $expires_at;
    $code->created_by = $campaign->created_by;

    $code->save();

    return response()->json([
      'status' => 'success',
      'token' => $token
    ], 200);
  }

  /**
   * Make sure code is unique
   *
   * @return boolean
   */
  public function getUniqueCode($type, $campaign_id)
  {
    if ($type == 'token') {
      $token = Str::random(8);
    }

    $code = Code::where('campaign_id', $campaign_id)->where('type', $type)->where('code', $token)->first();

    if ($code === null) {
      return $token;
    } else {
      return $this->getUniqueCode($type, $campaign_id);
    }
  }

  /**
   * Customer verifies code generated by merchant
   *
   * @return \Symfony\Component\HttpFoundation\Response
   */
  public function postVerifyCustomerCode(Request $request)
  {
    $account = app()->make('account');
    $campaign = \Platform\Models\Campaign::withoutGlobalScopes()->whereUuid(request('campaign', 0))->firstOrFail();
    $code = $request->code;

    // Set language locale
    $locale = request('locale', config('system.default_language'));
    app()->setLocale($locale);

    // Find code
    $code = Code::where('code', $code)->where('campaign_id', $campaign->id)->where('type', 'customer')->where('expires_at', '>', \Carbon\Carbon::now())->first();

    if ($code === null) {
      return response()->json([
        'status' => 'error',
        'errors' => ['code' => trans('campaign.code_invalid_or_expired')]
      ], 422);
    }

    $segments = $code->segments()->pluck('segments.id')->toArray();

    $history = new History;
    $history->customer_id = auth('customer')->user()->id;
    $history->campaign_id = $campaign->id;
    $history->staff_id = $code->staff_id;
    $history->staff_name = $code->staff_name;
    $history->staff_email = $code->staff_email;
    $history->points = $code->points;
    $history->event = 'Code entered by customer';
    $history->created_by = $campaign->created_by;

    $history->save();

    // Segments
    if (is_array($segments) && count($segments) > 0) {
      $history->segments()->sync($segments);
    }

    // Delete code
    $code->delete();

    return response()->json([
      'status' => 'success'
    ], 200);
  }

  /**
   * Customer verifies phone number given by merchant
   *
   * @return \Symfony\Component\HttpFoundation\Response
   */
  public function postVerifyPhoneNumber(Request $request)
  {
    $account = app()->make('account');
    $campaign = \Platform\Models\Campaign::withoutGlobalScopes()->whereUuid(request('campaign', 0))->firstOrFail();
    $code = $request->code;

    // Set language locale
    $locale = request('locale', config('system.default_language'));
    app()->setLocale($locale);

    // Find code
    $code = Code::where('code', $code)->whereNotNull('points')->where('campaign_id', $campaign->id)->where('type', 'phone')->where('expires_at', '>', \Carbon\Carbon::now())->first();

    if ($code === null) {
      return response()->json([
        'status' => 'error',
        'errors' => ['code' => trans('campaign.code_invalid_or_expired')]
      ], 422);
    }

    $segments = $code->segments()->pluck('segments.id')->toArray();

    $history = new History;
    $history->customer_id = auth('customer')->user()->id;
    $history->campaign_id = $campaign->id;
    $history->staff_id = $code->staff_id;
    $history->staff_name = $code->staff_name;
    $history->staff_email = $code->staff_email;
    $history->points = $code->points;
    $history->event = 'Code entered by customer';
    $history->created_by = $campaign->created_by;

    $history->save();

    // Segments
    if (is_array($segments) && count($segments) > 0) {
      $history->segments()->sync($segments);
    }

    // Delete code
    $code->delete();

    return response()->json([
      'status' => 'success'
    ], 200);
  }

  /**
   * Merchant verifies generated code
   *
   * @return \Symfony\Component\HttpFoundation\Response
   */
  public function postVerifyMerchantCode(Request $request)
  {
    $account = app()->make('account');
    $campaign = \Platform\Models\Campaign::withoutGlobalScopes()->whereUuid(request('campaign', 0))->firstOrFail();
    $code = $request->code;

    // Set language locale
    $locale = request('locale', config('system.default_language'));
    app()->setLocale($locale);

    // Find code
    $code = Code::where('code', $code)->where('campaign_id', $campaign->id)->where('type', 'merchant')->where('expires_at', '>', \Carbon\Carbon::now())->first();

    if ($code === null) {
      return response()->json([
        'status' => 'error',
        'errors' => ['code' => trans('campaign.code_invalid_or_expired')]
      ], 422);
    }

    // Code is correct, let merchant choose points and segments
    $segments = $campaign->business->segments->pluck('name', 'id');

    return response()->json([
      'status' => 'success',
      'segments' => $segments
    ], 200);
  }

  /**
   * Initially merhant code was correct, double check code and process points and segments
   *
   * @return \Symfony\Component\HttpFoundation\Response
   */
  public function postProcessMerchantEntry(Request $request)
  {
    $account = app()->make('account');
    $campaign = \Platform\Models\Campaign::withoutGlobalScopes()->whereUuid(request('campaign', 0))->firstOrFail();
    $code = $request->code;
    $points = $request->points;
    $segments = $request->segments;

    // Set language locale
    $locale = request('locale', config('system.default_language'));
    app()->setLocale($locale);

    // Find code
    $code = Code::where('code', $code)->where('campaign_id', $campaign->id)->where('type', 'merchant')->where('expires_at', '>', \Carbon\Carbon::now())->first();

    if ($code === null) {
      return response()->json([
        'status' => 'error',
        'errors' => ['code' => trans('campaign.code_invalid_or_expired')]
      ], 422);
    }

    // Code is correct, process points and segments

    $history = new History;
    $history->customer_id = auth('customer')->user()->id;
    $history->campaign_id = $campaign->id;
    $history->staff_id = $code->staff_id;
    $history->staff_name = $code->staff_name;
    $history->staff_email = $code->staff_email;
    $history->points = $points;
    $history->event = 'Code entered by staff member';
    $history->created_by = $campaign->created_by;

    $history->save();

    // Segments
    if (is_array($segments) && count($segments) > 0) {
      $history->segments()->sync($segments);
    }

    return response()->json([
      'status' => 'success'
    ], 200);
  }
}
